name: Ensure Alphabetical  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ensure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: nodejs console.log("test")
