name: Ensure Alphabetical  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ensure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          nodejs -e 'fs.readFile("servers_v8.json", (err, data) => {let servers = []; servers = JSON.parse(data); last = "a"; servers.forEach(s => {let l = s.name[0].toLowerCase(); if(l < last){throw "Serverlist is not alphabetical.";}else{last = l;}});});'
          nodejs -e 'fs.readFile("servers_test.json", (err, data) => {let servers = []; servers = JSON.parse(data); last = "a"; servers.forEach(s => {let l = s.name[0].toLowerCase(); if(l < last){throw "Serverlist is not alphabetical.";}else{last = l;}});});'
